name: AWS CDK Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  cdk-synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    
    # Add permissions needed for OIDC authentication
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to check out the repository
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt
          pip install awscli
          npm install -g aws-cdk
          
      - name: CDK Synth
        run: |
          cd infrastructure
          cdk synth
          
      - name: Upload CloudFormation template
        uses: actions/upload-artifact@v4
        with:
          name: cdk-templates
          path: infrastructure/cdk.out
          
  deploy-approval:
    name: Deployment Approval
    needs: cdk-synth
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}-approval
    # Add permissions needed for OIDC authentication
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to check out the repository
      
    steps:
      - name: Approve Deployment
        run: echo "Deployment to ${{ github.event.inputs.environment || 'dev' }} has been approved"
          
  cdk-deploy:
    name: CDK Deploy
    needs: deploy-approval
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    # Add permissions needed for OIDC authentication
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to check out the repository
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt
          pip install awscli
          npm install -g aws-cdk
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
          
      - name: Download CloudFormation template
        uses: actions/download-artifact@v4
        with:
          name: cdk-templates
          path: infrastructure/cdk.out
          
      - name: CDK Deploy
        run: |
          cd infrastructure
          cdk deploy --require-approval never
