name: AWS CDK Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  cdk-synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt
          npm install -g aws-cdk
          
      - name: CDK Synth
        run: |
          cd infrastructure
          cdk synth
          
      - name: Upload CloudFormation template
        uses: actions/upload-artifact@v3
        with:
          name: cdk-templates
          path: infrastructure/cdk.out
          
  deploy-approval:
    name: Deployment Approval
    needs: cdk-synth
    runs-on: ubuntu-latest
    environment: ${ github.event.inputs.environment || 'dev' }-approval
    steps:
      - name: Approve Deployment
        run: echo "Deployment to ${ github.event.inputs.environment || 'dev' } has been approved"
          
  cdk-deploy:
    name: CDK Deploy
    needs: deploy-approval
    runs-on: ubuntu-latest
    environment: ${ github.event.inputs.environment || 'dev' }
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt
          npm install -g aws-cdk
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${ secrets.AWS_ACCESS_KEY_ID }
          aws-secret-access-key: ${ secrets.AWS_SECRET_ACCESS_KEY }
          aws-region: ${ secrets.AWS_REGION }
          
      - name: Download CloudFormation template
        uses: actions/download-artifact@v3
        with:
          name: cdk-templates
          path: infrastructure/cdk.out
          
      - name: CDK Deploy
        run: |
          cd infrastructure
          cdk deploy --require-approval never
